lasp/adamant

default.do
default.elf.do
default.eps.do
default.gpr.do
default.o.do
default.pdf.do
default.png.do
default.svg.do
doc/user_guide/user_guide.tex
gen/generators/basic.py
gen/models/assembly.py
gen/models/base.py
gen/models/component.py
redo/database/_setup.py
redo/database/database.py
redo/database/model_cache_database.py
redo/rules/build_clear_cache.py
redo/rules/build_what.py
redo/util/filesystem.py
redo/util/performance.py
redo/util/redo_arg.py

This change introduces a model cache that is persistent across calls to `redo`. This allows the build system to run faster when it does not need to reread and revalidate YAML models that have not changed on disk. It also introduces a new command `redo clear_cache` that clears this cache for true clean building.

Persistant Model Caching

---

gen/templates/array/name.tex
gen/templates/enums/name.tex
gen/templates/memory_map/name.tex
gen/templates/record/name.tex
gen/templates/register_map/name.tex

Sometimes `\\` is not accepted by the compiler depending on what comes before in a .tex file. Using `vspace` works around this problem.

Fixing Latex Spacing in Preambles

---

gen/generators/basic.py
gen/generators/component.py
gen/generators/tests.py
gen/models/base.py
gen/models/tests.py
redo/database/model_cache_database.py

Fixing bug in model cache where creation of new submodel does not invalidate the cache for the parent model. This is now tracked by looking for a change in the submodels present on the filesystem for each model between builds.

Model Cache Bug Fix

---

alire.toml
gen/templates/memory_map/name.ads
gen/templates/register_map/name.ads
redo/targets/gpr/a_adamant.gpr

Updating to latest gprbuild, native compiler, and aunit. Disabling some warnings that are too cumbersome now.

Toolchain Update

---

redo/database/create.py
redo/rules/build_object.py

This supports the compilation of assembly files (asm) within the Adamant build system. There are no dependencies tracked between Ada and assembly or C/C++ and assembly. So, for now, you must compile assembly "manually" prior to linking by writing a custom `redo` file, or by other means. Assembly must use the file extension `.s`.

Assembly Compilation Support

---

redo/targets/riscv_bare_board.py

This just adds the bare board base target. Users can inherit from this to form actual RISC-V 32-bit build targets in their projects.

Adding bareboard support for riscv32

---

env/activate

This helps fix an issue on some SELinux systems where the docker bind mounts are owned by root.

Permissions Fix in Activate

---

doc/user_guide/build_user_guide.do
doc/user_guide/user_guide.tex
redo/rules/build_bindings.py
redo/util/redo_arg.py

Bindings are generated in separate subdirectories of `template/` for C/C++ bindings. Symbols for C++ differ based on compiler, so a single bindings file cannot work for any build target. This allows a user to generate bindings for different targets. The user guide has been updated to reflect this change.

Target-based C/C++ Binding Generation

---

redo/database/create.py
redo/rules/build_object.py

Previously only `.s` was supported. Now `.S` is also recognized as assembly and can be compiled.

Assembly support for .S suffix

---

env/activate
redo/targets/gpr/a_bareboard_base.gpr
redo/targets/gpr/a_bareboard_debug.gpr
redo/targets/gpr/a_bareboard_development.gpr
redo/targets/gpr/a_linux_debug_base.gpr

C++ compiler options are now consistent with C compiler options in the Adamant provided gpr file. This PR also includes:
- some white space fixes to gpr file
- modifying `$LD_LIBRARY_PATH` path in `activate` script to fix GLIBC linking issue that sometimes occurred when compiling C++

Adding C++ compiler options to gpr files

---

.github/workflows/build_user_guide.yml
.github/workflows/publish_all.yml
.github/workflows/style_all.yml
.github/workflows/test_all.yml

Since we now set the user to `user` at the end of the Dockerfile, we need to force GitHub to use the root user while running actions.

Updating github actions to use root user

---

default.do
env/activate
env/redo_completion.sh
redo/rules/build_what.py
redo/rules/build_what_predefined.py

Create the redo command `redo what_predefined`, which displays the commands listed in `redo what` which will always be listed regardless of the subdirectory of the project you're in.

`redo what` tab completion feature

---

doc/user_guide/user_guide.tex
redo/database/model_cache_database.py

This feature, while making builds faster, is unstable and produces a lot of hard to diagnose issues. I am disabling this for now. It can be enabled by setting the environment variable ENABLE_PERSISTANT_MODEL_CACHE to 1 manually. We can revisit this in the future if we want to re-enable.
This change forces Adamant to rebuild a new model cache with each call to redo instead of allowing it to persist over subsequent calls. Within a single redo call, the cache is still used to ensure a yaml file is only ever read from disk once maximum per call.

Disable the model cache by default

---

env/set_python_path.sh

This makes it more robust to when someone decides to create a python virtual environment in their adamant repo or something similar. This way we only find directories that are part of this repository.

Make set_python_path.sh only discover directories tracked by git

---

docker/adamant_env.sh

This adds the `pull` argument to the Docker container management script `adamant_env.sh`. This allows pulling and building new images with `./adamant_env.sh pull && ./adamant_env.sh start`, instead of having to remove/prune current images and running `./adamant_env.sh start` to pull the latest images.

Add `pull` to `adamant_env.sh`

---

env/activate

If a user did not remove their `alire/` directory when rebuilding their container environment, then the `alr` dependencies would not be downloaded and compiled correctly. This change ensures that every time a user logs in, the `alr` dependencies are rebuilt.

`activate` now always rebuilds `alr` dependencies.

---

src/components/fault_correction/gen/templates/fault_responses/name.ads

Follow on to: https://github.com/lasp/adamant/pull/58 to fix warnings found in https://github.com/lasp/adamant_example.

Fixes -gnatwj warnings in fault responses template

---

redo/rules/build_bindings.py
redo/rules/build_pretty.py
redo/rules/build_style.py

This commit applies gnatpp to the output of the bindings generator so that the generated code matches the Adamant coding style.

Generate C/C++ bindings with valid style

---

src/types/packed_arrays/packed_f64x3.array.yaml

For consistency, since we do not use the IEEE types anywhere else. If we want to transition to the IEEE types in the future, we should make that change wholesale. For now, we are consistently using the standard floating point types.

Using standard Long_Float type for Packed_F64 record instead of IEEE type

---

redo/database/c_source_database.py
redo/rules/build_bindings.py

This fixes an issue where bindings compilation works on a case-insensitive system like Mac, but fails on Linux.

Tweak capitalization on bindings generation

---

doc/example_architecture/parameter_component/component-parameter_component-implementation.ads
gen/templates/component/component-name-implementation.ads
gen/templates/component/component-name.adb
gen/templates/component/component-name.ads
src/components/limiter/component-limiter-implementation.ads
src/components/parameters/test/test_component_1/component-test_component_1-implementation.ads
src/components/parameters/test/test_component_2/component-test_component_2-implementation.ads
src/components/pid_controller/component-pid_controller-implementation.ads
src/types/parameter/parameter_enums.enums.yaml
src/types/parameter/parameter_table_header.record.yaml

This pull request adds the optionally implementable `Validate_Parameters` which allows a user to leverage custom inter-parameter validation in addition to individual component validation. This is optional, but components which have parameters will still have the default implementation of the action added to their respective generated templates.

Custom Parameter Validation within Component

---

src/unit_test/smart_assert/basic_assertions.ads

This pull request adds a new basic assertion for `system.address` types when unit testing. If merged, this would allow testing for memory address equality.

Add a new basic assertion for `system.address`

---

src/components/ccsds_command_depacketizer/gen/templates/assembly/name_ccsds_cosmos_commands.txt

This pull request updates the COSMOS plugin command template with improved name and length information for parameters.
Previous parameter name output produced identical parameter names for certain command parameter ranges, causing the compiled plugin to only contain one parameter when there should have been two.
Parameter length output was also incorrect for several commands with multiple appended parameters.
The revised behavior now includes the flattened name in addition to the field attributes when iterating over `type_model.flatten_dict()`. Parameter length is now calculated using `type_model.size`.

COSMOS Plugin Command Template Fixes

---

src/components/ccsds_serial_interface/ccsds_serial_interface.component.yaml
src/components/ccsds_serial_interface/component-ccsds_serial_interface-implementation.adb
src/components/ccsds_serial_interface/component-ccsds_serial_interface-implementation.ads

This allows the user to configure a gap (in ms) to be adhered to in between packets transmitted by the Ccsds_Serial_Interface component.

Add interpacket gap capability to Serial Interface

---

src/unit_test/string_util/bb/string_util.adb

This adds an implementation for the bareboard version of `To_Array_String` in `String_Util` package. This function was previously unimplemented, but can now be supported easily using the new Ada 2020 feature for `'Image` on Ada variables.

Add To_Array_String for bareboard String_Util

---

redo/targets/gpr/linux_analyze.gpr
redo/targets/gpr/linux_coverage.gpr
redo/targets/gpr/linux_debug.gpr

The compiler flags were not properly propogated through the abstract gpr files, so some options were getting lost for some languages. This fixes that issue so the compiler flags are passed properly through the abstract gpr files to the linux gpr files.

Fix compiler flags for Linux targets

---

env/activate

This modification to `activate` will cause it to look in the env/ directory in any adamant projects in the path. If a requirements*.txt file is found in that directory, it will attempt to pip install it. In this way, projects can declare their own specific python dependencies, that will then be automatically installed by Adamant along with the Adamant-specific dependencies.

Make `activate` install project py dependencies

---

redo/rules/build_test_all.py

This commit adds the `redo test` command output to `build/log/<test_name>.log` for each unit test run via `redo test_all`. This should assist in debugging tests that fail due to failed compilation.

Add `redo test` command logging to `redo test_all`

---

gen/generators/basic.py

This ensures that a model filename with capitalization in it still produces autocoded Ada that is all lower case.

Make basic generator robust to caps in filename

---

redo/rules/build_object.py

A `*_hpp.ads` or `*_h.ads` without a corresponding C/C++ dependency found in the build path now does not error out.

Relax dependency check for Ada binding of C/C++

---

gen/templates/array/name-validation.adb
gen/templates/array/name.adb
gen/templates/array/name.ads
gen/templates/record/name-validation.adb
gen/templates/record/name.adb
gen/templates/record/name.ads
gen/test/arrays/test/test.adb
gen/test/records/test/test.adb

Since Ada 2022 is supported throughout all of Adamant, these local pragmas are no longer necessary.

Remove unnecessary `pragma Ada_2022`s

---

gen/generators/packed_types.py
gen/templates/array/name-c.adb
gen/templates/array/name-c.ads
gen/templates/record/name-c.adb
gen/templates/record/name-c.ads

This allows the record conversions to work for types that previously failed compilation checks due to alignment constraints of aliased fields. This allows any packed record to produce a valid U_C type with conversion to U. In addition, new conversion functions have been added to convert directly from U_C to T and/or T_Le and back.

Update C packed type conversions

---

redo/rules/build_object.py

Fix `redo what` to only build objects for .c/.cpp

---

redo/rules/build_executable.py
redo/targets/gpr/a_adamant.gpr
redo/targets/gpr/linux_analyze.gpr
redo/targets/gpr/linux_coverage.gpr
redo/targets/gpr/linux_debug.gpr
redo/targets/gpr/linux_test.gpr

Linking to C/C++ would fail when only a portion of the C/C++ source files in a directory are dependencies of the currently compiling binary. Only some of the files would be compiled into objects, but GPRBuild (by default) tries to link to all C/C++ objects found in a directory in the Source_Dirs. To work around this, at link time, we now pass a list of files to exclude from the build, which includes C/C++ files that exist in the Source_Dirs, but are not dependencies of the currently compiling binary.

Fix for linking to unbuilt C/C++ objects

---

src/components/connector_queuer/connector_queuer.component.yaml

This component does not make sense as passive as implemented, and has been made active.

Make Connector Queue component active

---

redo/util/pydep.py

This pull request adds the following features to the `pydep.py` function:
- Accepts a list of files as arguments
- Adds 'verbose' mode with `-v` or `--verbose` arguments, which will output the previously implemented level of information
- Normal output now outputs the entire path to identified dependencies, without duplicates
- Adds `-i` or `--ignore` argument flags, which will ignore any packages containing an entry in the list of strings following the flag, for example:
```pydep -v sourceFile1.py sourceFile2.py -i ignore1 ignore2```
ignores any packages with names containing the strings "ignore1" or "ignore2"
- Catches exceptions when `ModuleNotFoundError` is thrown

Pydep function update

---

src/components/ccsds_packetizer/gen/templates/assembly/name_ccsds_cosmos_telemetry.txt

When generating the telemetry configuration for the COSMOS plugin, block data was only generated if the packet name was Events_Packet. Instead, the generator template now checks the packet item array, and produces the block data item in the correct case, similar to the Hydra template. Note that the CRC item is handled differently when the block data item is present, as the subpacket data has an indeterminate length at plugin compile time.

COSMOS Plugin Telemetry Fix

---

gen/models/record.py
gen/models/submodels/variable.py
src/components/ccsds_command_depacketizer/gen/generators/ccsds_commands.py
src/components/ccsds_command_depacketizer/gen/templates/assembly/name_ccsds_cosmos_commands.txt
src/components/ccsds_packetizer/gen/generators/ccsds_xml.py
src/components/ccsds_packetizer/gen/templates/assembly/name_ccsds_cosmos_telemetry.txt

The adamant modeling system can retrieve information about enum types for packed record/arrays either because a field is modeled using the adamant enum modeling features, or because type ranges have been loaded which can extract bare Ada enum information from hand written types. The way this enum information gets loaded into the packed record models was not uniform between these two methods and thus necessitated special handlig for each case, particularily in generator templates that need to output enum information.
This fix makes handling enums uniform, regardless of where the information is sourced. Checking .is_enum on a packed record or array field should tell the caller if the type of the field is an enum, and the literals can now always be accessed via .literals.

Fix consistency issue with enum modeling

---

gen/templates/array/name.ads
gen/templates/record/name.ads

This change provides convenient type aliases (using subtypes) for packed record fields and packed array elements. In this way, a user does not need to know the type of the field to reference it, they can simply use `<field_name>_Type`. For example, for the Sys_Time record, the autocoder now includes the following autocoded types for convenience:
```
subtype Seconds_Type is Interfaces.Unsigned_32;
subtype Subseconds_Type is Interfaces.Unsigned_32;
```

Packed Record Field Type Aliases

---

gen/templates/data_dependencies/name_data_dependencies.adb

When setting the ID and limits for a data product `_Stale_Limit` did not appear to be set. This presents as the default stale limit being used even when setting `map_data_dependencies: stale_limit_us:` in an assembly, and selecting `time: packet_time` in an extracted product.

Update data dependencies generator template to apply `_Stale_Limit`

---

gen/models/component.py
redo/rules/build_clean.py
redo/rules/build_executable.py
redo/rules/build_object.py

For `redo clean` as well as building binaries and executables.
For `redo clean` we now call out to the system to remove files using `rm` and we do this concurrently. This is much faster than using python's `rmtree`.
For building, the prebuild logic was making duplicate calls out to `redo-ifchange` during the prebuild phase. A refactor was able to eliminate these duplicate calls, improving build times.

Build system performance enhancements

---

gen/generators/packed_types.py
gen/models/record.py
gen/models/submodels/field.py
gen/models/type.py
gen/templates/array/name-assertion.adb
gen/templates/array/name-assertion.ads
gen/templates/record/name-assertion.adb
gen/templates/record/name-assertion.ads
gen/test/arrays/complex_float_array.array.yaml
gen/test/arrays/float_array.array.yaml
gen/test/arrays/test/test.adb
gen/test/records/ff.record.yaml
gen/test/records/gg.record.yaml
gen/test/records/test/test.adb
src/unit_test/smart_assert/smart_assert.adb

Add epsilon based assertions for packed types that include one or many floating point values. ie. an Eq comparison for a floating point value will return true if the two floating point values are less than or equal to +/- 1 epsilon apart.
When using the assertion package for a packed record or array that includes one or more floating point types, you can provide a single "Epsilon" argument as part of the assertion, which is used to compare all floating point types inside of the packed record or array. Non floating point types are still compared for exact equality (or inequality) as before. By default, if not specified, the value of Epsilon will be 0.0, resulting in the same behavior as before this feature existed.
New assertion calls with Epsilon look like:
```
Gg_U_Assert.Eq (G_U, (17, …
```

Add Epsilon Based Assertions for Packed Types

---

redo/util/pydep.py

This PR adds an optional argument flag to `pydep.py` which allows output of full filesystem paths of dependencies which have been built or exist statically in Adamant.
This may be used to programmatically build dependencies as before, but the additional output may be piped to a utility to perform other tasks, such as collect or copy these dependencies as needed.
An example of usage on a Python file which uses static and built imports:
```
python /adamant/redo/util/pydep.py example.py -p
```
The output:
```
All dependency paths:
/home/user/adamant/gnd/base_classes/packed_type_base.py
/home/user/adamant/gnd/util/crc_16.py
/home/user/adamant/src/types/packed_types/build/py/packed_f32.py
/home/user/adamant/src/types/parameter/build/py/parameter_table_header.py
```

Add path output to `pydep.py`

---

gnd/util/event_class_generator.py

Event parser now works for 16-bit subseconds in event messages as well as the standard 32-bit subseconds.

Handle 16-bit and 32-bit subseconds in event generator

---

src/components/ccsds_product_extractor/gen/templates/extracted_products/name.adb

This PR adjusts the Product Extractor autocode template to exclude the packages `Sys_Time` and `Ccsds_Space_Packet`, which already exist in the `name.ads` template. This change prevents duplication when a product extractor configuration includes one or both of these packages as a data product, but retains the corresponding `Validation` packages.

Preclude duplicates of hard-coded `with` clauses in Product Extractor

---

src/components/tick_divider/component-tick_divider-implementation.adb
src/components/tick_divider/component-tick_divider-implementation.ads
src/components/tick_divider/test/component-tick_divider-implementation-tester.adb
src/components/tick_divider/test/component-tick_divider-implementation-tester.ads
src/components/tick_divider/test/tests-implementation.adb
src/components/tick_divider/test/tests-implementation.ads
src/components/tick_divider/test/tests.tick_divider.tests.yaml
src/components/tick_divider/tick_divider.component.yaml

The component now supports two tick counting modes: Internal mode (default) uses an internal counter that increments with each received tick and rolls over at a calculated maximum to ensure proper divisor alignment. Tick_Counter mode uses the Count field from incoming ticks directly for division calculations, allowing external control of the counting sequence.

Add external tick counting mode to Tick Divider

---

gen/templates/tests/component-name_reciprocal.ads

Sometimes preambles in component models can cause unnecessary warnings in the reciprocal. It turns out that
```
pragma Warnings (Off, "unit ""{{ include }}"" is not referenced");
```
is not enough if the `with`ed package is still used in the body. An extra suppression has been added to fix that case.

Fix preamble warning in reciprocal .ads
